#default value = true
#liverefresh:
#  enable: true

spring:
  thymeleaf:
    cache: false
  
    
---
#production profile
 
spring:
  profiles: production
  thymeleaf:
    cache: true

liverefresh:
    enable: false