#default value = true
#liverefresh:
#  enable: true


security:
  basic:
    enabled: true
  user:
    name: user
    password: qwerty
    
spring:
  thymeleaf:
    cache: false
  
    
---
#production profile
 
spring:
  profiles: production
  thymeleaf:
    cache: true

liverefresh:
    enable: false