#default value = true
#liverefresh:
#  enable: true
#  ignore-file-changes:
#      - "/**/application.yml"
#      - "/**/git.properties"



logging:
  level:
    ru.vyukov.anotherliverefresh: DEBUG
  
  
---
#production profile
 
spring:
  profiles: production
  thymeleaf:
    cache: false

liverefresh:
    enable: false







---
#force enable profile
 
spring:
  profiles: force-enable

liverefresh:
    enable: true

    