#default value = true
#liverefresh:
#  enable: true


security:
  basic:
    enabled: true
  user:
    name: user
    password: qwerty
    
    
---
#production profile
 
spring:
  profiles: production

liverefresh:
    enable: false
    